# Generated by Django 4.2.5 on 2023-10-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to=''),
        ),
    ]
